### ISSUE TITLE
Wrong fetch options interface - ThreadMember#fetchOwner()

### ISSUE THREAD

**Issue by xCykz** [discordjs/docs#13]
https://discord.js.org/docs/packages/discord.js/14.16.3/ThreadChannel:Class#fetchOwner

As you can see it's 
fetchOwner(options?: **[BaseFetchOptions](https://discord.js.org/docs/packages/discord.js/14.16.3/BaseFetchOptions:Interface)**)
instead of 
fetchOwner(options?: **[FetchThreadMemberOptions](https://discord.js.org/docs/packages/discord.js/14.16.3/FetchThreadMemberOptions:Interface)**)

![image](https://github.com/user-attachments/assets/8b5a3c8f-2c06-4e83-aaf1-d1ec908b46e2)

**Comment by Qjuh** [comment]
- this is a repository only containing autogenerated docs json files, next time use the discord.js repository to report issues with the documentation or anything else djs
- The type in the documentation is indeed correct though, because you can‘t pass a `member` or `withMember` option into `fetchOwner()`, since it fetches the one single specific member that owns the thread. Leaving only the `BaseFetchOptions` like `force` or ` cache` to be acceptable parameters.

**Comment by xCykz** [comment]
Sorry for this.

Also I don't understand what you mean, `fetchOwner()` returns a **ThreadMember** not directly a **GuildMember**.
So to get the member you need to do something like `(await thread.fetchOwner({withMember: true})).guildMember;`
And guildMember returns `null` unless you pass tthis `withMember` option.

I had a little discussion on Discord as you can see here https://discord.com/channels/222078108977594368/824411059443204127/1299042327045869610

**Comment by Qjuh** [comment]
Oh, I see. In that case either types are wrong though. It does indeed accept `withMember`, but not `member`.
Could you please open this as an issue on https://github.com/discordjs/discord.js/ though? And imho `fetchOwner()` should use `withMember: true` by default, but apparently doesn't yet...

**Comment by xCykz** [comment]
Done https://github.com/discordjs/discord.js/issues/10578
